// interface Proposal

export const Proposals = [
    {    
        status: "",
        probationPeriod: 0,
        title: "Book Commission Initiative",
        shortDescription: "A student-led program to encourage book sharing, reduce financial strain, and promote a reading encourage book sharing, reduce financial strain, and promote a reading encourage book sharing, reduce financial strain, and promote a reading ",
        detailedDescription: "",
        numberOfVotes: 200,
        endDate: 3,
        likes: 20,
        dislikes: 30,
        yesVotes: 100,
        noVotes: 50,
        abstainVotes: 10,
        comments: 50,
    },
    {    
        status: "",
        probationPeriod: 0,
        title: "Book Exchange Initiative",
        shortDescription: "A student-led program to encourage book sharing, reduce financial strain, and promote a reading encourage book sharing, reduce financial strain, and promote a reading encourage book sharing, reduce financial strain, and promote a reading ",
        detailedDescription: "",
        numberOfVotes: 200,
        endDate: 3,
        likes: 20,
        dislikes: 30,
        yesVotes: 100,
        noVotes: 50,
        abstainVotes: 10,
        comments: 50,
    },
    {    
        status: "",
        probationPeriod: 0,
        title: "Book Exchange Initiative",
        shortDescription: "A student-led program to encourage book sharing, reduce financial strain, and promote a reading encourage book sharing, reduce financial strain, and promote a reading encourage book sharing, reduce financial strain, and promote a reading ",
        detailedDescription: "",
        numberOfVotes: 200,
        endDate: 3,
        likes: 20,
        dislikes: 30,
        yesVotes: 100,
        noVotes: 50,
        abstainVotes: 10,
        comments: 50,
    },
    {    
        status: "",
        probationPeriod: 0,
        title: "Book Exchange Initiative",
        shortDescription: "A student-led program to encourage book sharing, reduce financial strain, and promote a reading encourage book sharing, reduce financial strain, and promote a reading encourage book sharing, reduce financial strain, and promote a reading ",
        detailedDescription: "",
        numberOfVotes: 200,
        endDate: 3,
        likes: 20,
        dislikes: 30,
        yesVotes: 100,
        noVotes: 50,
        abstainVotes: 10,
        comments: 50,
    },
    
]